
POST http://localhost:3000/login HTTP/1.1

###

# {
#   "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDA1MTMwMjUsImlhdCI6MTYwMDUxMjk2NX0.cWu8kiLrm7jddcIRkjpvuWGnJzA0-HdByrenn_PonSE",
#   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDExMTc3NjUsImlhdCI6MTYwMDUxMjk2NX0.9PiNW3-csDlJj0H5eiOHH3Cq7MICiuJ4SGXSkMfgS2A"
# }
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDA1MTMwMjUsImlhdCI6MTYwMDUxMjk2NX0.cWu8kiLrm7jddcIRkjpvuWGnJzA0-HdByrenn_PonSE


###

POST http://localhost:3000/generate-token HTTP/1.1
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDExMTc3NjUsImlhdCI6MTYwMDUxMjk2NX0.9PiNW3-csDlJj0H5eiOHH3Cq7MICiuJ4SGXSkMfgS2A"
}

